#!/usr/bin/env python3
# local_analysis_model.py — bridges Qwen2.5-7B-Instruct (local, no fine-tuning)
# into ai_engine.py's Stage 2 analysis pipeline, replacing Groq.
#
# Also fixes the original bug this project set out to fix: frequency-in-prose
# is now derived DETERMINISTICALLY from the frequency code, never independently
# generated by the LLM — preventing contradictions like "Thrice a day" + "1-0-1".

import os
import json
import re
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

os.environ["TORCHDYNAMO_DISABLE"] = "1"
os.environ["PYTORCH_JIT"] = "0"

STAGE2_MODEL_PATH = os.path.expanduser("~/sanjeevani_project/stage2_model")

print("[local_analysis_model] Loading Stage 2 model (Qwen2.5-7B-Instruct)...")

_tokenizer = AutoTokenizer.from_pretrained(STAGE2_MODEL_PATH)
_model = AutoModelForCausalLM.from_pretrained(
    STAGE2_MODEL_PATH,
    torch_dtype=torch.bfloat16,
    device_map={"": 0},
    attn_implementation="sdpa",
)
_model.eval()

print("[local_analysis_model] Stage 2 model loaded and ready.")


FREQUENCY_CODE_MAP = {
    "1-0-1": "twice a day (morning and night)",
    "1-1-1": "three times a day (morning, afternoon, and night)",
    "0-0-1": "once a day (at night)",
    "1-0-0": "once a day (in the morning)",
    "1-1-0": "twice a day (morning and afternoon)",
    "0-1-1": "twice a day (afternoon and night)",
    "1-1-1-1": "four times a day",
}
FREQUENCY_WORD_MAP = {
    "od": "once a day", "once daily": "once a day",
    "bd": "twice a day", "twice daily": "twice a day",
    "tds": "three times a day", "tid": "three times a day", "thrice daily": "three times a day",
    "qid": "four times a day", "four times daily": "four times a day",
    "sos": "only as needed",
    "stat": "take immediately now",
}

def normalize_frequency(raw_frequency: str, dosage_text: str = "") -> str:
    combined = f"{raw_frequency} {dosage_text}".strip()

    code_match = re.search(r'\b(\d(?:-\d){1,3})\b', combined)
    if code_match:
        code = code_match.group(1)
        if code in FREQUENCY_CODE_MAP:
            return FREQUENCY_CODE_MAP[code]

    lower = combined.lower()
    for key, prose in FREQUENCY_WORD_MAP.items():
        if key in lower:
            return prose

    return raw_frequency.strip() if raw_frequency else "as directed"


def local_prescription_analysis(extracted_text: str, system_prompt: str, schema_prompt: str) -> dict:
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": schema_prompt},
    ]

    text = _tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    model_inputs = _tokenizer([text], return_tensors="pt").to(_model.device)

    with torch.no_grad():
        generated_ids = _model.generate(
            **model_inputs,
            max_new_tokens=2048,
            do_sample=False,
        )

    generated_ids_trimmed = generated_ids[:, model_inputs["input_ids"].shape[1]:]
    output_text = _tokenizer.batch_decode(generated_ids_trimmed, skip_special_tokens=True)[0]

    json_match = re.search(r'\{.*\}', output_text, re.DOTALL)
    if not json_match:
        print(f"[local_analysis_model] WARNING: no JSON found in output: {output_text[:300]}")
        return {}

    try:
        data = json.loads(json_match.group(0))
    except json.JSONDecodeError as e:
        print(f"[local_analysis_model] WARNING: JSON parse failed: {e}")
        return {}

    for med in data.get("medicines", []):
        raw_freq = med.get("frequency", "")
        dosage = med.get("dosage", "")
        med["frequency"] = normalize_frequency(raw_freq, dosage)

    return data
